# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4c23cc48d927f7c64c61ce7e74da932e"
name = "diversified-policy-app"
application_url = "https://since-vbulletin-oecd-journey.trycloudflare.com"
embedded = true
handle = "diversified-policy-app-17"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://since-vbulletin-oecd-journey.trycloudflare.com/auth/callback", "https://since-vbulletin-oecd-journey.trycloudflare.com/auth/shopify/callback", "https://since-vbulletin-oecd-journey.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

scopes = "read_products"